direct-read-namespaces = ["qqBot.trash", "qqBot.questions"]
change-stream-namespaces = ["qqBot.trash","qqBot.questions"]
mongo-url = "mongodb://mongo1:27017,mongo2:27017/qqBot?replicaSet=rs"
elasticsearch-urls = ["http://elasticsearch:9200"]
enable-http-server = true